from aim_fsm import *

class Kicker(StateMachineProgram):
  def setup(self):
      #     Kick() =C=> Print('Kicked') =C=> Kick()
      
      # Code generated by genfsm on Tue Aug 20 22:26:26 2024:
      
      kick1 = Kick() .set_name("kick1") .set_parent(self)
      print1 = Print('Kicked') .set_name("print1") .set_parent(self)
      kick2 = Kick() .set_name("kick2") .set_parent(self)
      
      completiontrans1 = CompletionTrans() .set_name("completiontrans1")
      completiontrans1 .add_sources(kick1) .add_destinations(print1)
      
      completiontrans2 = CompletionTrans() .set_name("completiontrans2")
      completiontrans2 .add_sources(print1) .add_destinations(kick2)
      
      return self

